# Generated by Django 3.0.3 on 2021-06-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210607_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
